
include("pipeline/generate_obs_logs.jl")
include("pipeline/make_masters.jl")
include("pipeline/mass_reduce.jl")
include("pipeline/make_table_and_plots.jl")
include("pipeline/generate_sequence.jl")
include("pipeline/make_template_psf.jl")
include("pipeline/register_frames.jl")
include("pipeline/rdi_subtract.jl")
include("pipeline/get_photometry.jl")