
include("reductions/generate_obs_logs.jl")
include("reductions/make_masters.jl")
include("reductions/mass_reduce.jl")
include("reductions/make_table_and_plots.jl")
include("reductions/generate_sequence.jl")
include("reductions/make_template_psf.jl")
include("reductions/register_frames.jl")
include("reductions/rdi_subtract.jl")
include("reductions/get_photometry.jl")